name: study_mate
description: A modern study dashboard app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  firebase_auth_web: ^5.10.0
  flutter_carousel_slider: ^1.1.0
  animated_bottom_navigation_bar: ^1.1.2
  flutter_staggered_grid_view: ^0.6.2
  liquid_pull_to_refresh: ^3.0.0
  badges: ^3.0.3
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.15.8
  http: ^1.2.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  flutter_bloc: ^8.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/studymate.png
    - assets/images/study_mate_bg_clean.png

